In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df1=pd.read_csv("Preprocess_Bank_churners.csv")
df1

,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,0.437506,-0.165406,1.059956,0.503368,-0.052637,-0.628128,-0.574182,-0.259473,0.384621,0.763943,-1.327136,0.492404,0.446622,-0.473422,0.488971,2.623494,-0.959707,-0.973895,3.834003,-0.775882
1,0.437506,0.333570,-0.943436,2.043199,-0.597678,0.727306,0.755053,-0.259473,1.010715,1.407306,-1.327136,-0.411616,-0.041367,-0.366667,-0.008486,3.563293,-0.916433,-1.357340,12.608573,-0.616276
2,0.437506,0.583058,1.059956,0.503368,-0.597678,-0.628128,0.090436,-0.259473,0.008965,0.120579,-1.327136,-2.219655,-0.573698,-1.426858,-0.445658,8.367214,-0.740982,-1.911206,6.807864,-0.997155
3,0.437506,-0.789126,-0.943436,1.273283,-0.052637,2.082739,0.755053,-0.259473,-0.241473,-0.522785,1.641478,-1.315636,-0.585251,1.661686,-0.734100,2.942843,-0.951758,-1.911206,6.807864,1.759686
4,0.437506,-0.789126,1.059956,0.503368,1.037447,-0.628128,-0.574182,-0.259473,-1.869317,0.763943,-1.327136,-2.219655,-0.430877,-1.426858,-0.302868,6.455682,-1.056263,-1.570365,7.509325,-0.997155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,0.437506,0.458314,1.059956,-0.266547,-0.597678,0.727306,-1.238799,-0.259473,0.509840,-0.522785,-0.337598,0.492404,-0.509330,0.844455,-0.584929,-0.259771,3.259358,2.221481,0.608119,0.678714
10123,-2.285681,-0.664382,1.059956,-0.266547,1.582489,-1.983561,-1.238799,-0.259473,-1.368442,0.120579,-0.337598,0.492404,-0.479181,1.255524,-0.591639,0.201004,1.283475,0.176440,-0.122745,0.856458
10124,-2.285681,-0.290150,-0.943436,-1.036462,-0.052637,-0.628128,0.755053,-0.259473,0.008965,0.763943,0.651940,1.396424,-0.354626,-1.426858,-0.226632,0.269436,1.732994,-0.207005,0.444305,-0.997155
10125,-2.285681,-2.036565,1.059956,-0.266547,-0.597678,2.082739,-1.238799,-0.259473,0.008965,0.120579,0.651940,0.492404,-0.368710,-1.426858,-0.240713,-1.026208,1.174848,-0.121795,0.041070,-0.997155
10126,-2.285681,-0.414894,-0.943436,-0.266547,-0.597678,-0.628128,0.755053,4.069499,-1.368442,1.407306,-0.337598,1.396424,0.193220,0.979433,0.105372,-0.259771,1.733877,-0.164400,-0.265557,-0.311572

In [3]:
df1.columns

Index(['Attrition_Flag', 'Customer_Age', 'Gender', 'Dependent_count',
       'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category',
       'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio'],
      dtype='object')

In [4]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import train_test_split
import numpy as np

# Convert Attrition_Flag to binary
y = np.where(df1['Attrition_Flag'] > 0, 1, 0)
X = df1.drop(columns=['Attrition_Flag'])

# Define and fit the feature selector (e.g., SelectKBest)
fit1 = SelectKBest(score_func=f_classif, k=7)  # Select top 10 features
fit1.fit(X, y)

# Select columns based on the feature selector
selected_columns = X.columns[fit1.get_support(indices=True)]

# Filter the selected columns from X
X_selected = X[selected_columns]

# Split data into train and test sets for evaluation
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Random Forest
print("\nRandom Forest:")
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
# Predictions and Evaluation on Test Data
y_pred_test_rf = rf.predict(X_test)
print("Random Forest Accuracy on Test Data:", accuracy_score(y_test, y_pred_test_rf))
print("Classification Report (Test Data):")
print(classification_report(y_test, y_pred_test_rf))

Random Forest:
Random Forest Accuracy on Test Data: 0.9496544916090819
Classification Report (Test Data):
              precision    recall  f1-score   support

           0       0.89      0.79      0.83       327
           1       0.96      0.98      0.97      1699

    accuracy                           0.95      2026
   macro avg       0.92      0.88      0.90      2026
weighted avg       0.95      0.95      0.95      2026

## Conclusion

## Therefore, Random Forest model achieved 95% accuracy, indicating their strong performance on the given dataset. This suggests that model effectively capture the underlying patterns and trends in the data.

## Deployment

In [7]:
# Save the model
import pickle
filename = "finalised_model.pkl"
with open(filename, 'wb') as file:
    pickle.dump(rf, file)

print(f"Model saved as {filename}")

Model saved as finalised_model.pkl